server:
  port: 8040
spring:
  data:
    mongodb:
      username: mustufa
      password: mustufa
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.dev.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.dev.ecommerce.kafka.payment.PaymentConfirmation
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          trust: "*"
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000